---
- name:  Terraform Init
  block:
    - name: "[terraform.common] initializing terraform"
      community.general.terraform:
        backend_config: '{{ backend_config | default(omit) }}'
        backend_config_files: '{{ backend_config_files | default(omit) }}'
        binary_path: '{{ binary_path | default(omit) }}'
        check_destroy: '{{ check_destroy }}'
        complex_vars: '{{ complex_vars }}'
        force_init: '{{ force_init }}'
        init_reconfigure: '{{ init_reconfigure }}'
        lock: '{{ lock }}'
        lock_timeout: '{{ lock_timeout | default(omit) }}'
        overwrite_init: '{{ overwrite_init }}'
        parallelism: '{{ parallelism  | default(omit) }}'
        plan_file: '{{ plan_file | default(omit) }}'
        plugin_paths: '{{ plugin_paths | default(omit) }}'
        project_path: '{{ project_path }}'
        provider_upgrade: '{{ provider_upgrade }}'
        purge_workspace: '{{ purge_workspace }}'
        state: '{{ state }}'
        state_file: '{{ state_file | default(omit) }}'
        targets: '{{ targets | default(omit) }}'
        variables: '{{ variables | default(omit) }}'
        variables_files: '{{ variable_files | default(omit) }}'
        workspace: '{{ workspace  }}'
      check_mode: '{{ enable_check_mode }}'
      register: terraform_result