---
# Tasks file for pre-tasks
- block:
    - ansible.builtin.stat:
        path: '{{ project_path }}'
      register: _project_path
  
    - name: "[role.git] cloning '{{ repo_uri }}' to '{{ project_path }}'"
      include_tasks: checkout.yml
      register: git_checkout
      when: _project_path.stat.exists == false
