---
- block:
  - name: "[role.terraform] terraform apply"
    include_tasks: terraform.yml
    vars:
      state: present
      _check_mode: false
    when: _plan_file.stat.exists == false
  
  - ansible.builtin.copy:
      src: '{{ inventory_file }}'
      dest: '{{ playbook_dir }}'