---
# tasks file for terraform
- block:
  - name: "[role.terraform] setting terraform command"
    ansible.builtin.set_fact:
      command: '{{ item.value.name }}'
      state: '{{ item.value.state }}'
    when: "'{{ tf_command }}' is in item.key"
    loop: "{{ lookup('ansible.builtin.vars', 'terraform_command') }}"

  - ansible.builtin.debug:
      var: '{{ item }}'
    with_items:
      - '{{ command }}'
      - '{{ state}}'
    
#- ansible.builtin.set_fact:
#    state: '{{ state }}'

#- ansible.builtin.debug:
#    var: state

#- include_tasks: template.yml

#- ansible.builtin.stat:
#    path: '{{ plan_file }}'
#  register: _plan_file

#- include_tasks: plan.yml
#  when: state == "planned" or state == "present" and _plan_file.stat.exists == false

#- include_tasks: destroy.yml
#  when: state == "absent"
