---
# tasks file for terraform
- block:
  - name: "[role.terraform] setting terraform command"
    ansible.builtin.set_fact:
      tf_command: "{{ lookup('ansible.builtin.vars', 'state') }}"

  - ansible.builtin.debug:
      var: tf_command
    
#- ansible.builtin.set_fact:
#    state: '{{ state }}'

#- ansible.builtin.debug:
#    var: state

#- include_tasks: template.yml

#- ansible.builtin.stat:
#    path: '{{ plan_file }}'
#  register: _plan_file

#- include_tasks: plan.yml
#  when: state == "planned" or state == "present" and _plan_file.stat.exists == false

#- include_tasks: destroy.yml
#  when: state == "absent"
